### ISSUE TITLE
Adding Windows support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/oniguruma-feedstock#1]
Would be nice to have a Windows build. Particularly to provide support for a fully functional `jq` on Windows. ( https://github.com/conda-forge/jq-feedstock/issues/3 )

**Comment by jankatins** [comment]
What's the problem here?

This is the pacman build file for mingw: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-oniguruma/PKGBUILD

**Comment by jakirkham** [comment]
Simply lack of knowledge on my part. I don't even have a Windows dev environment so it is pretty brutal for me to add this stuff. The few times I have tried it is basically using AppVeyor to even do the prototyping. If you are interested in giving this a try, I would be happy to add Windows support here.

**Comment by jakirkham** [comment]
So this might be more doable with 6.0.0 as it comes with CMake support.

**Comment by jakirkham** [comment]
Put together PR ( https://github.com/conda-forge/oniguruma-feedstock/pull/18 ), which may resolve this.
